### ISSUE TITLE
gfcli build error: [FATA] Error: exit status 128

### ISSUE THREAD

**Issue by colorfullee** [gogf/gf-cli#140]
**Your project is awsome ! Everything is ok when i use `go run main.go`, But something confuses me When i finish my project and try to build it, The console throws an error** `[FATA] Error: exit status 128` 
Here is my project build config in `/manifest/config/config.yaml`
```
gfcli:
  build:
    name: "gf"
    arch: "all"
    system: "all"
    mod: "none"
    cgo: 0
    pack: ""
    version: "v0.0.1"
    output: "./bin"
    extra: ""
```

Project environment(gf version)：
```
GoFrame CLI Tool v2.0.0, https://goframe.org 
GoFrame Version: cannot find goframe requirement in go.mod 
CLI Installed At: /usr/local/bin/gf 
CLI Built Detail:
  Go Version:  go1.17.4
  GF Version:  v2.0.0-beta
  Git Commit:  2021-12-16 01:03:53 9295e29f2b2819faf4acb65d409931d445911faa
  Build Time:  2021-12-15 17:03:23
```
About my OS：
```
MacOS BigSur
CPU : Intel Core i7 2 GHz
RAM : 16 GB 2400 MHz
```
I'm looking forward to your answer! **Thanks!**
